### ISSUE TITLE
By Deno, Unable to install

### ISSUE THREAD

**Issue by yoshixmk** [yoshixmk/gagic#2]
There is an error about the default properties, and cannot install Gagic.
- https://github.com/denoland/deno/issues/7455

```ts
error: Uncaught TypeError: Cannot read property 'default' of undefined
            exports_48("React", react_16_13_1_1.default);
                                                ^
    at execute (file:///Users/yu/.deno/bin/gagic.js:26797:49)
    at gExp (file:///Users/yu/.deno/bin/gagic.js:90:7)
    at gExp (file:///Users/yu/.deno/bin/gagic.js:89:47)
    at __instantiate (file:///Users/yu/.deno/bin/gagic.js:97:27)
    at file:///Users/yu/.deno/bin/gagic.js:184921:15
```

**Comment by yoshixmk** [comment]
If you don't install it, it will work, so please use the method below as an alternative.

```bash
$ deno run --unstable --allow-read --allow-write --allow-net https://raw.githubusercontent.com/yoshixmk/gagic/master/mod.ts build
```

**Comment by yoshixmk** [comment]
Resolved this.
